"""stage record tables and codex conformance

The seven per-stage payload tables carried forward from v1 (04 §5.2), the
`apiary_locations` they snapshot from, and `codex_conformance` (P3-C, 10 §6).

Autogenerated against a scratch database and then hand-reviewed. The review
found the one thing autogenerate reliably misses: it created the
`conformance_verdict` enum type on the way up and did not drop it on the way
down, which would leave the type orphaned and make a later `upgrade` fail on a
duplicate. `tests/test_migrations.py` asserts against exactly that gap.

Revision ID: 4f58f6313266
Revises: cd6efa0b7cd3
Create Date: 2026-08-06 14:36:15.719136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f58f6313266"
down_revision: str | Sequence[str] | None = "cd6efa0b7cd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apiary_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farmer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("altitude", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("vegetation_type", sa.String(), nullable=True),
        sa.Column("hive_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["farmer_id"], ["farmers.id"], name=op.f("fk_apiary_locations_farmer_id_farmers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apiary_locations")),
    )
    op.create_index(
        op.f("ix_apiary_locations_farmer_id"), "apiary_locations", ["farmer_id"], unique=False
    )
    op.create_table(
        "apiary_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("apiary_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("altitude", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("vegetation_type", sa.String(), nullable=True),
        sa.Column("hive_count", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["apiary_id"],
            ["apiary_locations.id"],
            name=op.f("fk_apiary_records_apiary_id_apiary_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_apiary_records_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apiary_records")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_apiary_records_batch_id")),
    )
    op.create_table(
        "batch_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("honey_type", sa.String(), nullable=False),
        sa.Column("expected_yield_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("harvest_window_start", sa.Date(), nullable=False),
        sa.Column("harvest_window_end", sa.Date(), nullable=False),
        sa.Column("apiary_management_method", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_batch_metadata_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_metadata")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_batch_metadata_batch_id")),
    )
    op.create_table(
        "codex_conformance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("rule_set_version", sa.String(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("PASS", "FAIL", "INCOMPLETE", name="conformance_verdict"),
            nullable=False,
        ),
        sa.Column("moisture_passed", sa.Boolean(), nullable=True),
        sa.Column("fructose_glucose_passed", sa.Boolean(), nullable=True),
        sa.Column("sucrose_passed", sa.Boolean(), nullable=True),
        sa.Column("hmf_passed", sa.Boolean(), nullable=True),
        sa.Column("diastase_passed", sa.Boolean(), nullable=True),
        sa.Column("free_acidity_passed", sa.Boolean(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_codex_conformance_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_codex_conformance")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_codex_conformance_batch_id")),
    )
    op.create_table(
        "distribution_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("retailer_name", sa.String(), nullable=False),
        sa.Column("transport_reference", sa.String(), nullable=True),
        sa.Column("handover_notes", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_distribution_records_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distribution_records")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_distribution_records_batch_id")),
    )
    op.create_table(
        "harvest_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("harvest_date", sa.DateTime(), nullable=False),
        sa.Column("quantity_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hive_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gps_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("gps_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_harvest_records_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harvest_records")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_harvest_records_batch_id")),
    )
    op.create_table(
        "lab_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("moisture_pct", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fructose_glucose_g_100g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sucrose_g_100g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("hmf_mg_kg", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("diastase_schade", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("free_acidity_meq_kg", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pollen_density", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("laboratory_name", sa.String(), nullable=True),
        sa.Column("analyst_name", sa.String(), nullable=True),
        sa.Column("certificate_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("tested_at", sa.DateTime(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["honey_batches.id"], name=op.f("fk_lab_results_batch_id_honey_batches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_results")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_lab_results_batch_id")),
    )
    op.create_table(
        "packaging_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("jar_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_packaging_records_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packaging_records")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_packaging_records_batch_id")),
    )
    op.create_table(
        "process_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("extraction_method", sa.String(), nullable=False),
        sa.Column("moisture_content", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("handling_notes", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["honey_batches.id"],
            name=op.f("fk_process_records_batch_id_honey_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_records")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_process_records_batch_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("process_records")
    op.drop_table("packaging_records")
    op.drop_table("lab_results")
    op.drop_table("harvest_records")
    op.drop_table("distribution_records")
    op.drop_table("codex_conformance")
    op.drop_table("batch_metadata")
    op.drop_table("apiary_records")
    op.drop_index(op.f("ix_apiary_locations_farmer_id"), table_name="apiary_locations")
    op.drop_table("apiary_locations")
    # ### end Alembic commands ###
    # Added by hand: autogenerate creates the enum type with the table but
    # never drops it, so a downgrade would orphan it and the next upgrade
    # would fail on "type already exists".
    op.execute("DROP TYPE IF EXISTS conformance_verdict")
